# Generated by Django 2.2.1 on 2019-12-03 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='precio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Precio'),
            preserve_default=False,
        ),
    ]
