# Generated by Django 2.2.1 on 2019-12-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lugar_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='url',
        ),
        migrations.AddField(
            model_name='lugar',
            name='latitud',
            field=models.CharField(default=100.2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lugar',
            name='longitud',
            field=models.CharField(default=50.2, max_length=30),
            preserve_default=False,
        ),
    ]
