# Generated by Django 2.2.1 on 2019-12-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191203_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenas',
            name='lugar',
            field=models.CharField(max_length=30),
        ),
    ]
